context:
  name: altair-aitools-devkit
  version: 1.0rc1
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/altair-aitools-devkit/${{ version }}/altair_aitools_devkit-${{ version }}.tar.gz
  sha256: 410550a1c0dbda2f4297d8a2ef6a0a8386ab2746cab5fe2c23501964a333d0f5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - build-extension = altair_aitools.dev._builder:build_extension
      - create-extension = altair_aitools.dev._create_extension:create_extension

requirements:
  host:
    - python ==${{ python_min }}
    - hatchling
    - pip
  run:
  - python >=${{ python_min }}
  - networkx >=3.0
  - pipdeptree >=2.20
  - pyyaml >=6.0
  - conda-index >=0.5.0,<0.6
  - conda-lock >=2.5,<2.6
  - libmambapy >=2.0
  - altair-aitools-runtime >=1.0rc1

tests:
  - python:
      imports:
        - altair_aitools.ext
        - altair_aitools.dev
  - requirements:
      run:
        - pip
    script:
      - pip check
      - build-extension --help
      - create-extension --help

about:
  summary: altair-aitools-devkit is a comprehensive package that provides a set of tools to develop Altair RapidMiner AI tools extensions in Python
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://altair.com/altair-rapidminer

extra:
  recipe-maintainers:
    - skontar-altair
    - pczako-altair
