github:
  branch_name: main
  tooling_branch_name: main
# conda_build:
#   error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
bot:
  automerge: false
  check_solvable: true
  update_dependencies: false